default interface client-texture {
    use pkg.types.{ulid}

    variant format {
        rgba8-unorm
    }

    record descriptor2d {
        width: u32,
        height: u32,
        format: format,
        data: list<u8>,
    }

    record handle {
        ulid: ulid
    }

    create2d: func(desc: descriptor2d) -> handle
    destroy: func(handle: handle)
}
