default interface client-message {
    use pkg.types.{entity-id}

    variant source {
        remote,
        local(entity-id),
    }

    variant target {
        remote-unreliable,
        remote-reliable,
        local-broadcast,
        local(entity-id),
    }

    send: func(target-id: target, name: string, data: list<u8>)
}