default interface client-mesh {
    use pkg.types.{vec2, vec3, ulid}

    record vertex {
        position: vec3,
        normal: vec3,
        tangent: vec3,
        texcoord0: vec2,
    }

    record handle {
        ulid: ulid
    }

    create: func(vertices: list<vertex>, indices: list<u32>) -> handle
}
