default interface client-mesh {
    use pkg.types.{vec2, vec3, ulid}

    record vertex {
        position: vec3,
        normal: vec3,
        tangent: vec3,
        texcoord0: vec2,
    }

    record descriptor {
        vertices: list<vertex>,
        indices: list<u32>,
    }

    record handle {
        ulid: ulid
    }

    create: func(desc: descriptor) -> handle
    destroy: func(handle: handle)
}
