default interface client-camera {
    use pkg.types.{vec2, ray, entity-id}

    clip-space-ray: func(camera: entity-id, clip-space-pos: vec2) -> ray
    screen-to-clip-space: func(screen-pos: vec2) -> vec2
    screen-to-world-direction: func(camera: entity-id, screen-pos: vec2) -> ray
}