record run-context {
    time: float32,
}

init: func()
exec: func(ctx: run-context, event-name: string, event-data: list<tuple<u32, component-type>>)

// TEMPORARY: until we move to the component model, we have to duplicate definitions
// and convert between the import and guest representations... :(
record entity-id {
    id0: u64,
    id1: u64,
}

record vec2 {
    x: float32,
    y: float32,
}

record vec3 {
    x: float32,
    y: float32,
    z: float32,
}

record vec4 {
    x: float32,
    y: float32,
    z: float32,
    w: float32,
}

record quat {
    x: float32,
    y: float32,
    z: float32,
    w: float32,
}

record mat4 {
    x: vec4,
    y: vec4,
    z: vec4,
    w: vec4,
}

record object-ref {
    id: string,
}

variant component-list-type {
    type-empty(list<tuple<>>),
    type-bool(list<bool>),
    type-entity-id(list<entity-id>),
    type-f32(list<float32>),
    type-f64(list<float64>),
    type-mat4(list<mat4>),
    type-i32(list<s32>),
    type-quat(list<quat>),
    type-string(list<string>),
    type-u32(list<u32>),
    type-u64(list<u64>),
    type-vec2(list<vec2>),
    type-vec3(list<vec3>),
    type-vec4(list<vec4>),
    type-object-ref(list<object-ref>),
}

variant component-option-type {
    type-empty(option<tuple<>>),
    type-bool(option<bool>),
    type-entity-id(option<entity-id>),
    type-f32(option<float32>),
    type-f64(option<float64>),
    type-mat4(option<mat4>),
    type-i32(option<s32>),
    type-quat(option<quat>),
    type-string(option<string>),
    type-u32(option<u32>),
    type-u64(option<u64>),
    type-vec2(option<vec2>),
    type-vec3(option<vec3>),
    type-vec4(option<vec4>),
    type-object-ref(option<object-ref>),
}

variant component-type {
    type-empty(tuple<>),
    type-bool(bool),
    type-entity-id(entity-id),
    type-f32(float32),
    type-f64(float64),
    type-mat4(mat4),
    type-i32(s32),
    type-quat(quat),
    type-string(string),
    type-u32(u32),
    type-u64(u64),
    type-vec2(vec2),
    type-vec3(vec3),
    type-vec4(vec4),
    type-object-ref(object-ref),
    type-list(component-list-type),
    type-option(component-option-type),
}
