default interface guest {
    use pkg.component.{component-type}

    init: func(interface-version: u32)
    exec: func(time: float32, event-name: string, event-data: list<tuple<u32, component-type>>)
}