world bindings {
    import types: pkg.types

    import component: pkg.component
    import entity: pkg.entity
    import event: pkg.event

    import client-message: pkg.client-message
    import client-player: pkg.client-player

    import server-physics: pkg.server-physics
    import server-asset: pkg.server-asset
    import server-message: pkg.server-message

    export guest: pkg.guest
}