world bindings {
    import types: pkg.types

    import asset: pkg.asset
    import component: pkg.component
    import entity: pkg.entity
    import message: pkg.message
    import player: pkg.player
    import world-audio: pkg.world-audio

    import client-audio: pkg.client-audio
    import client-message: pkg.client-message
    import client-player: pkg.client-player
    import client-input: pkg.client-input
    import client-camera: pkg.client-camera
    import client-window: pkg.client-window
    import client-mesh: pkg.client-mesh
    import client-material: pkg.client-material
    import client-texture: pkg.client-texture

    import server-physics: pkg.server-physics
    import server-message: pkg.server-message

    export guest: pkg.guest
}
