default interface server-message {
    use pkg.types.{entity-id}

    variant source {
        network(string),
        module(entity-id),
    }

    variant target {
        network-broadcast-unreliable,
        network-broadcast-reliable,
        network-targeted-unreliable(string),
        network-targeted-reliable(string),
        module-broadcast,
        module(entity-id),
    }

    send: func(target-id: target, name: string, data: list<u8>)
}