interface world-audio {
    use types.{entity-id, vec3, quat}
    set-listener: func(entity: entity-id)
    set-emitter: func(entity: entity-id, amp: float32)
    play-sound-on-entity: func(sound: string, emitter: entity-id)
}