#![allow(missing_docs)]

// Hi there! The components, concepts and messages are generated by a macro
// and are not visible.
// We suggest that you look at the docs for this crate.
// Your IDE should also tell you about the contents and show their corresponding
// doc comments.
ambient_api_macros::api_project!();
