default world wasi {
  import wasi-monotonic-clock: pkg.wasi-monotonic-clock
  import wasi-wall-clock: pkg.wasi-wall-clock
  import wasi-timezone: pkg.wasi-timezone
  import wasi-default-clocks: pkg.wasi-default-clocks
  import wasi-logging: pkg.wasi-logging
  import wasi-stderr: pkg.wasi-stderr
  import wasi-filesystem: pkg.wasi-filesystem
  import wasi-random: pkg.wasi-random
  import wasi-poll: pkg.wasi-poll
  import wasi-io: pkg.wasi-io
  import wasi-default-network: pkg.wasi-default-network
  import wasi-ip-name-lookup: pkg.wasi-ip-name-lookup
  import wasi-tcp: pkg.wasi-tcp
  import wasi-udp: pkg.wasi-udp
  import wasi-network: pkg.wasi-network
  import wasi-exit: pkg.wasi-exit
  import wasi-environment: pkg.wasi-environment
}
