/// # Prototype stderr API
///
/// This is a simple non-line-aware synchronous infallible output device,
/// suitable for implementing stderr.
default interface wasi-stderr {
    /// Print text to stderr.
    print: func(message: string)

    /// Test whether stderr is known to be a terminal.
    ///
    /// This is similar to `isatty` in POSIX.
    is-terminal: func() -> bool

    /// If stderr is a terminal and the number of columns can be determined,
    /// return it.
    num-columns: func() -> option<u16>
}
