/// # WASI Random API
///
/// WASI Random is a random data API.
///
/// It is intended to be portable at least between Unix-family platforms and
/// Windows.
default interface wasi-random {
  /// Return `len` random bytes.
  ///
  /// This function must produce data from an adaquately seeded CSPRNG, so it
  /// must not block, and the returned data is always unpredictable.
  ///
  /// Deterministic environments must omit this function, rather than
  /// implementing it with deterministic data.
  get-random-bytes: func(len: u32) -> list<u8>

  /// Return a random `u64` value.
  ///
  /// This function must produce data from an adaquately seeded CSPRNG, so it
  /// must not block, and the returned data is always unpredictable.
  ///
  /// Deterministic environments must omit this function, rather than
  /// implementing it with deterministic data.
  get-random-u64: func() -> u64
}
